site_name: Endurain documentation
repo_url: https://github.com/joaovitoriasilva/endurain
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Integrations:
    - 3rd party apps: integrations/3rd-party-apps.md
    - 3rd party services: integrations/3rd-party-services.md
  - Developer guide: developer-guide.md